Update for MedievalCities to work with CoreBlocks
Terasology/MedievalCities pull request #1
Opened 2019-09-29 15:43 UTC by Qwertygiy

Updates all the references from Core to CoreBlocks.

2019-09-29 17:30 UTC, skaldarnar reviewed
Did you run a test world with these changes? Do you have a screenshot by chance showing that the buildings still look right after the change?

2019-09-30 19:03 UTC, skaldarnar approved these changes

2019-09-30 19:04 UTC, skaldarnar requested changes

2019-09-30 19:04 UTC, skaldarnar commented on module.txt
> +        }
Wait, there's a `}` too much here o.O
```suggestion
```

2019-09-30 22:12 UTC, merged

2019-09-30 23:42 UTC, Qwertygiy commented
Tested and appearing to work as intended:
![image](https://cdn.discordapp.com/attachments/270264625419911192/628368009529917441/unknown.png)